services:
  auth:
    image: music-auth
    ports:
      - "3000:3000"
    env_file:
      - ../auth/.env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
